# This workflow will build & upload a Python Package to TestPyPi using Twine 
# whenever a PR is merged or a commit is made to the master branch.

name: Build and Publish Package to TestPyPi

# This workflow will run when a PR is merged or when a commit is made directly to the master branch.
# ref: https://github.community/t/trigger-workflow-only-on-pull-request-merge/17359/3
on:
  push:
    branches: [ main ]
  # pull_request:
    # The branches below must be a subset of the branches above
    # branches: [ master ]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python' ]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python' ]
        # Learn more:
        # https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning#changing-the-languages-that-are-analyzed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
        # If you wish to specify custom queries, you can do so here or in a config file.
        # By default, queries listed here will override any specified in a config file.
        # Prefix the list here with "+" to use these queries and those in the config file.
        # queries: ./path/to/local/query, your-org/your-repo/queries@main

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

  build-and-publish-testpypi:
    name: Build and publish distributions to TestPyPI
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: 🔨Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        skip_existing: true

  # deploy:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@master
  #   - name: Set up Python 3.6
  #     uses: actions/setup-python@v1
  #     with:
  #       python-version: 3.6
  #   - name: Install pypa/build
  #     run: >-
  #       python -m
  #       pip install
  #       build
  #       --user
  #   - name: Build a binary wheel and a source tarball
  #     run: >-
  #       python -m
  #       build
  #       --sdist
  #       --wheel
  #       --outdir dist/
  #       .
  #   - name: Publish distribution 📦 to PyPI
  #     uses: pypa/gh-action-pypi-publish@master
  #     with:
  #       password: ${{ secrets.PYPI_API_TOKEN }}
