# This workflow will build & upload a Python Package to TestPyPi using Twine 
# whenever a PR is merged or a commit is made to the master branch.

name: Build and Publish Package to TestPyPi

# This workflow will run when a PR is merged or when a commit is made directly to the master branch.
# ref: https://github.community/t/trigger-workflow-only-on-pull-request-merge/17359/3
on:
  push:
    branches: [ master ]

jobs:
  build-and-publish:
    name: Build and publish distributions to TestPyPI
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: 🔨Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        skip_existing: true
